---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cnpg-operator
  namespace: flux-system
spec:
  interval: 1h0m0s
  path: ./clusters/base/addons/cnpg-operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-sync
