---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: democratic-csi
  namespace: flux-system
spec:
  releaseName: democratic-csi
  targetNamespace: democratic-csi
  interval: 30m
  chart:
    spec:
      chart: democratic-csi
      version: 0.14.6
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
  valuesFrom:
    - kind: Secret
      name: democratic-csi-values
  driftDetection:
    mode: enabled
  postRenderers:
    - kustomize:
        patches:
          # Disable leader election
          - target:
              version: v1
              kind: Deployment
              name: democratic-csi-controller
            patch: |
              - op: remove
                path: /spec/template/spec/containers/0/args/2
              - op: remove
                path: /spec/template/spec/containers/0/args/1
              - op: remove
                path: /spec/template/spec/containers/1/args/2
              - op: remove
                path: /spec/template/spec/containers/1/args/1
              - op: remove
                path: /spec/template/spec/containers/2/args/2
              - op: remove
                path: /spec/template/spec/containers/2/args/1
              - op: remove
                path: /spec/template/spec/containers/3/args/2
              - op: remove
                path: /spec/template/spec/containers/3/args/1
  values:
    csiDriver:
      name: org.democratic-csi.freenas-nfs
    fsGroupPolicy: File
    storageClasses:
      - name: truenas-nfs
        defaultClass: false
        parameters:
          fsType: nfs
        mountOptions:
          - noatime
          - nfsvers=4
    driver:
      config:
        driver: freenas-api-nfs
        instance_id: org.democratic-csi.truenas-nfs
        httpConnection:
          protocol: https
          host: ${truenas_host}
          port: ${truenas_port}
          allowInsecure: true
          apiKey: ${truenas_api_key}
        zfs:
          datasetParentName: tank/k8s/${cluster_name}/volumes
          detachedSnapshotsDatasetParentName: tank/k8s/${cluster_name}/snapshots
        nfs:
          shareHost: 10.0.30.126
          shareAllDirs: false
          shareAllowHosts: []
          shareAllowNetworks:
            - 10.0.30.0/24
