# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: sergelogvinov
  namespace: flux-system
spec:
  type: oci
  interval: 24h
  url: oci://ghcr.io/sergelogvinov/charts
