---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: addons
  namespace: flux-system
spec:
  interval: 1h0m0s
  path: ./clusters/kairos/addons
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
