apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-addons
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-settings
  path: ./clusters/${CLUSTER_NAME}/addons
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
  interval: 1m
