apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: democratic-csi
  namespace: flux-system
spec:
  interval: 1h0m0s
  path: ./clusters/base/addons/democratic-csi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
