# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/addons/gateway-api/
  - ./cilium.yaml
  - ./cilium-configs.yaml
  - ./external-dns.yaml
  - ./monitoring.yaml
  - ./cert-manager.yaml
  - ./cert-manager-issuers.yaml
  # - ../../base/addons/cloudflare-gateway/
  # - ./cloudflare-gateway-configs.yaml
  - ./cnpg-operator.yaml
  # - ./democratic-csi.yaml
  # - ./proxmox-ccm.yaml
  - ./proxmox-csi.yaml
patches:
  - target:
      group: kustomize.toolkit.fluxcd.io
      kind: Kustomization
    patch: |-
      - op: add
        path: /spec/retryInterval
        value: 1m
      - op: add
        path: /spec/postBuild
        value:
          substituteFrom:
            - kind: ConfigMap
              name: cluster-values
            - kind: Secret
              name: cluster-secrets
      - op: add
        path: /spec/decryption
        value:
          provider: sops
          secretRef:
            name: sops-age
