---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: flux-system
spec:
  releaseName: cilium
  targetNamespace: kube-system
  storageNamespace: kube-system
  interval: 30m
  chart:
    spec:
      chart: cilium
      version: 1.15.3
      sourceRef:
        kind: HelmRepository
        name: cilium
      interval: 12h
  values:
    k8sServiceHost: 10.0.30.30
    k8sServicePort: 6443
    kubeProxyReplacement: strict
    ipam:
      # mode: kubernetes
      # mode: cluster-pool
      operator:
        clusterPoolIPv4PodCIDRList:
          - 10.42.0.0/16
    operator:
      replicas: 1
      rollOutPods: true
    rollOutCiliumPods: true
    gatewayAPI:
      enabled: true
    # k8s-require-ipv4-pod-cidr: true
    # bpf:
    #   masquerade: true
      # hostLegacyRouting: true
    bgpControlPlane:
      enabled: true

    bpf:
      masquerade: true
      hostLegacyRouting: false
      lbExternalClusterIP: true
    routingMode: native
    ipv4NativeRoutingCIDR: 10.42.0.0/16
    autoDirectNodeRoutes: true

    loadBalancer:
      mode: dsr
    tunnel: disabled

    # localRedirectPolicy: true
    hubble:
      ui:
        enabled: true
        rollOutPods: true
      relay:
        enabled: true
        rollOutPods: true
    # securityContext:
    #   capabilities:
    #     ciliumAgent:
    #       - CHOWN
    #       - KILL
    #       - NET_ADMIN
    #       - NET_RAW
    #       - IPC_LOCK
    #       - SYS_ADMIN
    #       - SYS_RESOURCE
    #       - DAC_OVERRIDE
    #       - FOWNER
    #       - SETGID
    #       - SETUID
    #     cleanCiliumState:
    #       - NET_ADMIN
    #       - SYS_ADMIN
    #       - SYS_RESOURCE
    # cgroup:
    #   autoMount:
    #     enabled: false
    #   hostRoot: /sys/fs/cgroup
