keys:
  - &kid-nixos age1dghfu7sxwlkf4626eywmgr63y2g7m4x8zs8a6xt2zay3x7dclpnsw776dd
  - &talos-kidibox-net age1d3fhnsrjptnrvelew39xux2mes4d9zt8eyem3q5mpccav5g4fg6su9mx29
  - &clusters-home age1d3fhnsrjptnrvelew39xux2mes4d9zt8eyem3q5mpccav5g4fg6su9mx29

defaults: &defaults
  key_groups:
    - age:
        - *kid-nixos

creation_rules:
  - path_regex: clusters/home/.+\.sops\.ya?ml
    encrypted_regex: ^(data|stringData)$
    key_groups:
      - age:
          - *kid-nixos
          - *clusters-home
  - path_regex: clusters/talos.kidibox.net/.+\.sops\.ya?ml
    encrypted_regex: ^(data|stringData)$
    key_groups:
      - age:
          - *kid-nixos
          - *talos-kidibox-net
  - path_regex: clusters/talos.kidibox.net/.+\.sops\.env
    key_groups:
      - age:
          - *kid-nixos
          - *talos-kidibox-net
  - <<: *defaults

stores:
  yaml:
    indent: 2
