---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: proxmox-csi
  namespace: flux-system
spec:
  releaseName: proxmox-csi
  targetNamespace: proxmox-csi
  interval: 30m
  chart:
    spec:
      chart: proxmox-csi-plugin
      version: 0.2.5
      sourceRef:
        kind: HelmRepository
        name: sergelogvinov
  valuesFrom:
  - kind: Secret
    name: proxmox-csi-values
