cluster:
  name: talos.kidibox.net
externalServices:
  prometheus:
    host: https://prometheus-prod-01-eu-west-0.grafana.net
    basicAuth:
      username: "609653"
  loki:
    host: https://logs-prod-eu-west-0.grafana.net
    basicAuth:
      username: "303796"
  tempo:
    host: https://tempo-eu-west-0.grafana.net:443
    basicAuth:
      username: "300309"
metrics:
  enabled: true
  alloy:
    metricsTuning:
      useIntegrationAllowList: true
  cost:
    enabled: false
  kepler:
    enabled: true
  node-exporter:
    enabled: true
logs:
  enabled: true
  pod_logs:
    enabled: true
  cluster_events:
    enabled: true
traces:
  enabled: true
receivers:
  grpc:
    enabled: true
  http:
    enabled: true
  zipkin:
    enabled: false
  grafanaCloudMetrics:
    enabled: false
opencost:
  enabled: false
  opencost:
    exporter:
      defaultClusterId: talos.kidibox.net
    prometheus:
      external:
        url: https://prometheus-prod-01-eu-west-0.grafana.net/api/prom
kube-state-metrics:
  enabled: true
prometheus-node-exporter:
  enabled: true
prometheus-operator-crds:
  enabled: true
kepler:
  enabled: true
alloy: {}
alloy-events: {}
alloy-logs: {}
