---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cloudflare-kubernetes-gateway
  namespace: flux-system
spec:
  interval: 24h
  url: https://github.com/pl4nty/cloudflare-kubernetes-gateway
  ref:
    tag: v0.6.0
