apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: monitoring
  namespace: flux-system
spec:
  releaseName: monitoring
  targetNamespace: monitoring
  interval: 30m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: k8s-monitoring
      version: 1.4.8
      sourceRef:
        kind: HelmRepository
        name: grafana
  valuesFrom:
    - kind: Secret
      name: monitoring-values
