apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - ./namespace.yaml
  - ./helm-release.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: monitoring-values
    files:
      - values.yaml
