VERSION 0.8

FROM alpine:edge

ARG EARTHLY_GIT_SHORT_HASH
ARG --global version=${EARTHLY_GIT_SHORT_HASH}
ARG --global IMAGE_REPOSITORY=ghcr.io/kid/home-infra

build:
	ARG --required container
	FROM DOCKERFILE ${container}
	LABEL org.opencontainers.image.source = "https://github.com/kid/home-infra"
	SAVE IMAGE --push ${IMAGE_REPOSITORY}/${container}:latest
	SAVE IMAGE --push ${IMAGE_REPOSITORY}/${container}:${version}

all:
	LOCALLY
	FOR container IN $(ls -d */)
		BUILD \
			--platform=linux/amd64 \
			--platform=linux/arm64 \
			+build \
			--container="${container%/}"
	END
