apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: ${cluster_name}
  namespace: cloudflare-gateway
spec:
  gatewayClassName: cloudflare
  listeners:
    - name: http
      protocol: HTTP
      port: 80
