apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway-api
  namespace: flux-system
spec:
  path: ./config/crd/experimental
  prune: false
  sourceRef:
    kind: GitRepository
    name: gateway-api
  interval: 24h
