---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: democratic-csi
  namespace: flux-system
spec:
  releaseName: democratic-csi
  targetNamespace: democratic-csi
  interval: 30m
  chart:
    spec:
      chart: democratic-csi
      version: 0.14.6
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
  valuesFrom:
  - kind: Secret
    name: democratic-csi-values
