---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: proxmox-ccm
  namespace: flux-system
spec:
  releaseName: proxmox-ccm
  targetNamespace: proxmox-ccm
  interval: 30m
  chart:
    spec:
      chart: proxmox-cloud-controller-manager
      version: 0.2.4
      sourceRef:
        kind: HelmRepository
        name: sergelogvinov
  valuesFrom:
  - kind: Secret
    name: proxmox-ccm-values
