---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
  name: gateways
spec:
  nodeSelector:
    matchLabels: {}
  virtualRouters:
    - localASN: 64512
      exportPodCIDR: false
      neighbors:
        - peerAddress: '${router_ip}/32'
          peerASN: 64512
      serviceSelector:
        matchExpressions:
          - {key: "io.cilium.gateway/owning-gateway", operator: Exists}
