---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: flux-system
spec:
  releaseName: cilium
  targetNamespace: kube-system
  interval: 30m
  chart:
    spec:
      chart: cilium
      version: 1.15.7
      sourceRef:
        kind: HelmRepository
        name: cilium
  valuesFrom:
    - kind: ConfigMap
      name: cilium-values
  values:
    operator:
      replicas: 3
      rollOutPods: true
    rollOutCiliumPods: true
    gatewayAPI:
      enabled: true
    bgpControlPlane:
      enabled: true
