---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: flux-system
  annotations:
    kustomize.toolkit.fluxcd.io/prune: Disabled
spec:
  releaseName: cilium
  targetNamespace: kube-system
  interval: 30m
  chart:
    spec:
      chart: cilium
      version: 1.15.7
      sourceRef:
        kind: HelmRepository
        name: cilium
  values:
    operator:
      replicas: 1
      rollOutPods: true
    rollOutCiliumPods: true
    gatewayAPI:
      enabled: true
    bgpControlPlane:
      enabled: true
