# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare
  namespace: cloudflare-gateway
type: Opaque
stringData:
  ACCOUNT_ID: ${cloudflare_account_id}
  TOKEN: ${cloudflare_api_token}
