#cloud-config

strict: true

install:
  auto: true
  reboot: true

hostname: ${hostname}

users:
  - name: kairos
    shell: /usr/bin/bash
    groups:
      - admin
    ssh_authorized_keys:
      - github:kid

p2p:
  role: ${role}
  network_token: ${kairos_p2p_token}
  disable_dht: true
  vpn:
    create: false
    use: false

kubevip:
  eip: ${kubevip_eip}
