#cloud-config

strict: true

install:
  auto: true
  reboot: true
  bundles:
    - targets:
      - run://ghcr.io/kid/kairos-bundles-timoni:latest

hostname: ${hostname}
users:
  - name: kairos
    shell: /usr/bin/bash
    groups:
      - admin
    ssh_authorized_keys:
      - github:kid

p2p:
  role: ${role}
  network_token: ${kairos_p2p_token}
  disable_dht: true
  vpn:
    create: false
    use: false

kubevip:
  eip: ${kubevip_eip}

k3s:
  args:
    - --flannel-backend=none
    - --disable-helm-controller
    - --disable-network-policy
    - --disable=local-storage,servicelb,traefik

timoni:
  bundles:
    - url: https://raw.githubusercontent.com/kid/home-infra/feat/talos/kubernetes/flux-aio.cue
