---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gateway-api
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/kid/home-infra
  ref:
    branch: main
