apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: webhook
  namespace: flux-system
spec:
  parentRefs:
  - name: talos.kidibox.net
    namespace: cloudflare-gateway
  hostnames:
  - flux-talos.kidibox.net
  rules:
  - backendRefs:
    - name: notification-controller
      port: 80
