---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  releaseName: cert-manager
  targetNamespace: cert-manager
  interval: 30m
  chart:
    spec:
      chart: cert-manager
      version: 1.14.5
      sourceRef:
        kind: HelmRepository
        name: jetstack
      interval: 12h
  values:
    installCRDs: true
    prometheus:
      enabled: false
    featureGates: "ExperimentalGatewayAPISupport=true"
