apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: proxmox-csi
  namespace: flux-system
spec:
  interval: 1h
  approvePlan: auto
  path: ./terraform/stacks/proxmox-csi/
  backendConfig:
    disable: true
  cliConfigSecretRef:
    name: tfe-cli-config
  sourceRef:
    kind: GitRepository
    name: cluster
    namespace: flux-system
  vars:
    - name: cluster_name
      value: "${CLUSTER_NAME}"
  writeOutputsToSecret:
    name: proxmox-csi
  runnerPodTemplate:
    spec:
      volumes:
        - name: sops-age
          secret:
            secretName: sops-age
      volumeMounts:
        - name: sops-age
          mountPath: /home/runner/.config/sops/age/keys.txt
          subPath: age.agekey
          readOnly: true
      env:
        - name: SOPS_AGE_KEY_FILE
          value: /home/runner/.config/sops/age/keys.txt
