---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flux
  namespace: flux-system
spec:
  releaseName: flux
  targetNamespace: kube-system
  interval: 30m
  chart:
    spec:
      chart: flux2
      version: 2.13.0
      sourceRef:
        kind: HelmRepository
        name: flux
  # valuesFrom:
  #   - kind: ConfigMap
  #     name: flux-values
