apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - ./cluster-secrets.sops.yaml
configMapGenerator:
  - name: cluster-settings
    envs:
      - ../../cluster.env
generatorOptions:
  disableNameSuffixHash: true
