apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: proxmox-csi
  namespace: flux-system
spec:
  path: ./clusters/${CLUSTER_NAME}/addons/proxmox-csi
  prune: true
  dependsOn:
    - name: proxmox-csi-stack
  sourceRef:
    kind: GitRepository
    name: cluster
  interval: 1m
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
      - kind: Secret
        name: proxmox-csi
