---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns
resources:
  - ./namespace.yaml
  - ./manifest.yaml
secretGenerator:
  - name: powerdns
    literals:
      - EXTERNAL_DNS_PDNS_SERVER=${pdns_api_url}
      - EXTERNAL_DNS_PDNS_API_KEY=${pdns_api_key}

generatorOptions:
  disableNameSuffixHash: true
