---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns

resources:
  - ./namespace.yaml
  - ./manifest.yaml

# FIXME: does not get replaced by flux's kustomize :/
# need kustomize to generate stringData
# secretGenerator:
#   - name: powerdns
#     literals:
#        - EXTERNAL_DNS_PDNS_SERVER=${powerdns_api_url}
#        - EXTERNAL_DNS_PDNS_API_KEY=${powerdns_api_key}
