---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  dependsOn:
    - name: gateway-api
    - name: cilium
  interval: 1h0m0s
  path: ./clusters/kairos/addons/cert-manager/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
