---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-configs
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager
  interval: 1h0m0s
  path: ./clusters/kairos/addons/cert-manager/configs
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
  decryption:
    provider: sops
    secretRef:
      name: sops-age
