apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  annotations:
    kustomize.toolkit.fluxcd.io/prune: Disabled
spec:
  releaseName: cilium
  targetNamespace: kube-system
  interval: 30m
  chart:
    spec:
      chart: cilium
      version: 1.16.4
      sourceRef:
        kind: HelmRepository
        name: cilium
  valuesFrom:
    - kind: ConfigMap
      name: cilium-values
  values:
    routingMode: native
    autoDirectNodeRoutes: true
    ipv4NativeRoutingCIDR: 10.244.0.0/16
    # bpf:
    #   masquerade: true
    #   hostLegacyRouting: false
    gatewayAPI:
      enabled: true
    bgpControlPlane:
      enabled: true
