---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp
spec:
  nodeSelector:
    matchLabels: {}
  bgpInstances:
    - name: default
      localASN: 64512
      peers:
        - name: router
          peerASN: 64512
          peerAddress: "${NETWORK_ROUTER_IP}"
          peerConfigRef:
            name: router
