apiVersion: batch/v1
kind: CronJob
metadata:
  name: recyclarr
  labels:
    app.kubernetes.io/component: recyclarr
    app.kubernetes.io/instance: downloadarr
    app.kubernetes.io/name: recyclarr
spec:
  suspend: false
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 30
  schedule: "@daily"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 6
      template:
        metadata:
          labels:
            app.kubernetes.io/component: recyclarr
            app.kubernetes.io/instance: downloadarr
            app.kubernetes.io/name: recyclarr
        spec:
          enableServiceLinks: false
          serviceAccountName: default
          automountServiceAccountToken: true
          securityContext:
            fsGroup: 1215
            fsGroupChangePolicy: OnRootMismatch
            runAsGroup: 1215
            runAsNonRoot: true
            runAsUser: 3005
            seccompProfile:
              type: RuntimeDefault
          hostIPC: false
          hostNetwork: false
          hostPID: false
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          containers:
            - args:
                - sync
                - -c
                - /recyclarr.yml
              env:
                - name: TZ
                  value: Europe/Brussels
              envFrom:
                - secretRef:
                    name: api-keys
              image: ghcr.io/recyclarr/recyclarr:7.2.4@sha256:1bf2436ed4749a4309765dd21643aac858dd436a536e37c25bb463513601e962
              name: app
              resources:
                limits:
                  memory: 128Mi
                requests:
                  cpu: 10m
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                readOnlyRootFilesystem: true
              volumeMounts:
                - mountPath: /config
                  name: config
                - mountPath: /recyclarr.yml
                  name: config-file
                  readOnly: true
                  subPath: recyclarr.yml
                  # - mountPath: /config/logs
                  #   name: config-logs
          volumes:
            - name: config
              persistentVolumeClaim:
                claimName: recyclarr
            - configMap:
                name: recyclarr-config
              name: config-file
          # - emptyDir: {}
          #   name: config-logs
