---
# Instance: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  labels:
    app.kubernetes.io/managed-by: timoni
    app.kubernetes.io/name: flux-system
    app.kubernetes.io/version: 2.3.0-0
  name: flux-system
  namespace: flux-system
spec:
  interval: 60m
  path: clusters/talos.kidibox.net
  prune: true
  retryInterval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 3m
  wait: true
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  labels:
    app.kubernetes.io/managed-by: timoni
    app.kubernetes.io/name: flux-system
    app.kubernetes.io/version: 2.3.0-0
  name: flux-system
  namespace: flux-system
spec:
  ignore: clusters/**/flux-system/
  interval: 1m
  ref:
    name: refs/heads/main
  url: https://github.com/kid/home-infra.git
