# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  labels:
    app: prowlarr
spec:
  selector:
    matchLabels:
      app: prowlarr
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: prowlarr
      labels:
        app: prowlarr
    spec:
      containers:
        - name: prowlarr
          image: ghcr.io/linuxserver/prowlarr:1.21.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9696
              name: http
          livenessProbe:
            httpGet:
              path: /ping
              port: http
          readinessProbe:
            httpGet:
              path: /ping
              port: http
          env:
            - name: PUID
              value: '1000'
            - name: PGID
              value: '1000'
            - name: TZ
              value: Europe/Brussels
            - name: PROWLARR__APP__THEME
              value: dark
            - name: PROWLARR__AUTH__METHOD
              value: External
            - name: PROWLARR__AUTH__REQUIRED
              value: DisabledForLocalAddresses
            - name: PROWLARR__LOG__ANALYTICSENABLED
              value: "False"
            - name: PROWLARR__LOG__LEVEL
              value: info
            - name: PROWLARR__LOG__DBENABLED
              value: "False"
            - name: PROWLARR__POSTGRES__MAINDB
              valueFrom:
                secretKeyRef:
                  name: prowlarr-pg-app
                  key: dbname
            - name: PROWLARR__POSTGRES__HOST
              valueFrom:
                secretKeyRef:
                  name: prowlarr-pg-app
                  key: host
            - name: PROWLARR__POSTGRES__PORT
              valueFrom:
                secretKeyRef:
                  name: prowlarr-pg-app
                  key: port
            - name: PROWLARR__POSTGRES__USER
              valueFrom:
                secretKeyRef:
                  name: prowlarr-pg-app
                  key: user
            - name: PROWLARR__POSTGRES__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: prowlarr-pg-app
                  key: password
      restartPolicy: Always
