apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: prowlarr-pg
spec:
  instances: 2
  storage:
    size: 10Gi
    storageClass: proxmox-local-zfs-ext4
  bootstrap:
    initdb:
      database: prowlarr
      owner: prowlarr
      # secret:
      #   name: prowlarr-pg
