# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./gotk-components.yaml
  - ./gotk-sync.yaml
patches:
  - path: ./patches/namespace.yaml
    target:
      kind: Namespace
      name: flux-system
  - path: ./patches/resourcequota.yaml
    target:
      kind: ResourceQuota
      name: flux
