apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml

patches:
- target:
    kind: Namespace
    name: flux-system
  patch: |-
    - op: add
      path: /metadata/labels/pod-security.kubernetes.io~1enforce
      value: privileged
- target:
    kind: Deployment
    labelSelector: app.kubernetes.io/part-of=flux
  patch: |-
    - op: replace
      path: /spec/template/spec/hostNetwork
      value: true
    - op: remove
      path: /spec/template/spec/containers/0/livenessProbe
    - op: remove
      path: /spec/template/spec/containers/0/readinessProbe
    - op: add
      path: /spec/template/spec/tolerations
      value:
      - key: node.kubernetes.io/not-ready
    - op: remove
      path: /spec/template/spec/containers/0/ports
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: KUBERNETES_SERVICE_HOST
        value: "127.0.0.1"
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: KUBERNETES_SERVICE_PORT
        value: "7445"
