apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
patches:
- target:
    kind: Namespace
    name: flux-system
  patch: |-
    - op: add
      path: /metadata/labels/pod-security.kubernetes.io~1enforce
      value: privileged

