apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
patches:
- target:
    kind: Deployment
    labelSelector: app.kubernetes.io/part-of=flux
  patch: |-
    - op: replace
      path: /spec/template/spec/hostNetwork
      value: true
    - op: add
      path: /spec/template/spec/tolerations
      value:
      - key: node.kubernetes.io/not-ready
