# vim: set ft=yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
patches:
- target:
    group: kustomize.toolkit.fluxcd.io
    version: v1
    kind: Kustomization
    name: flux-system
  patch: |
    spec:
      apiVersion: kustomize.toolkit.fluxcd.io/v1
      metadata:
        name: flux-system
      decryption:
        provider: sops
        secretRef:
          name: sops-age
