---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cluster
  namespace: flux-system
spec:
  interval: 1m
  secretRef:
    name: github-deploy-key
  url: ssh://git@github.com/kid/home-infra
  ref:
    branch: ${CLUSTER_BRANCH}
  ignore: |
    # exclude all
    /*
    # include base and cluster directory
    !/clusters/_base
    !/clusters/${CLUSTER_NAME}
    # exclude bootstrap folder
    /clusters/${CLUSTER_NAME}/bootstrap
    # required for terraform stacks
    !/secrets
    !/terraform
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-settings
  namespace: flux-system
spec:
  interval: 1m
  path: ./clusters/${CLUSTER_NAME}/flux/settings
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: cluster
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-settings
  interval: 1m
  path: ./clusters/${CLUSTER_NAME}
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: cluster
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
