apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: servarr
  namespace: flux-system
spec:
  path: ./clusters/home/apps/servarr
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: cluster
  interval: 1m
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
