# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: servarr
resources:
  - ../../../_base/apps/servarr/
secretGenerator:
  - name: api-keys
    envs:
      - api-keys.sops.env
