# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tofu-controller
  namespace: flux-system
spec:
  releaseName: tofu-controller
  targetNamespace: flux-system
  interval: 30m
  chart:
    spec:
      chart: tf-controller
      version: 0.16.0-rc.4
      sourceRef:
        kind: HelmRepository
        name: tofu-controller
  values:
    awsPackage:
      install: false
    runner:
      image:
        repository: ghcr.io/kid/home-infra/tofu-runner
