---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium
  namespace: flux-system
spec:
  dependsOn:
    - name: gateway-api
  interval: 1h0m0s
  path: ./kubernetes/cluster-addons/cilium/manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-addons
