apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium
  namespace: flux-system
spec:
  dependsOn:
    - name: gateway-api
  path: ./kubernetes/cluster-addons/cilium/manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-addons
  interval: 24h
  retryInterval: 1m
  timeout: 5m
  wait: true
