# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg-operator
  namespace: flux-system
spec:
  releaseName: cnpg-operator
  targetNamespace: cnpg-system
  interval: 30m
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.24.0
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
