name: dagger

permissions:
  # For Azure Authentication
  id-token: write
  contents: read
  issues: write
  pull-requests: write

on:
  push:
    branches: [main]
  pull_request: {}

jobs:
  build:
    name: terraform
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v3
      - uses: dagger/dagger-for-github@v5
        env:
          ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
          ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
          ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}
        with:
          verb: call
          module: ci/terraform
          args: --source . ci-remote --commit "${GITHUB_SHA}" --chdir terraform/configs/bootstrap --armClientId "${ARM_CLIENT_ID}" --armSubscriptionId "${ARM_SUBSCRIPTION_ID}" --armTenantId "${ARM_TENANT_ID}" --actionsIdTokenRequestUrl "${ACTIONS_ID_TOKEN_REQUEST_URL}" --actionsIdTokenRequestToken "${ACTIONS_ID_TOKEN_REQUEST_TOKEN}"
