---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
  name: bgp-peering-policy
spec:
  nodeSelector:
    matchLabels: {}
  virtualRouters:
    - localASN: 64512
      exportPodCIDR: false
      neighbors:
        - peerAddress: '10.0.30.1/32'
          peerASN: 64512
      serviceSelector:
        matchExpressions:
          - {key: "bgp-advertise", operator: In, values: ['true']}
